# Generated by Django 5.1.1 on 2024-09-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("marca", models.CharField(max_length=100)),
                ("fecha_vencimiento", models.DateField()),
            ],
        ),
    ]
